services:
  elasticsearch:
      image: elasticsearch:8.12.0
      container_name: elasticsearch
      restart: always
      volumes:
        - elasticsearch_data:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
      environment:
        - DISCOVERY_SERVICE=single-node
        - ES_JAVA_OPTS=-Xms3g -Xmx3g
        - bootstrap.memory_lock=true
        # - node.name=elasticsearch
      ulimits: # Resource limits for the container
        memlock: # prevents memory from being swapped out to disk
          soft: -1 #unlimited memory locking
          hard: -1
        nofile: #maximum number of open file descriptors
          soft: 65536
          hard: 65536
      networks:
        - my_network

  kibana:
    image: kibana:8.12.0
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    networks:
      - my_network
  # FluentBit?
volumes:
  elasticsearch_data:

networks:
  my_network:
    driver: bridge